#!/bin/sh

# If run with the "config"-parameter, give out information on how the
# graphs should look.

mystatuscodes="400 401 403 404 500 503 504"
myloglines="10000"
myaccesslog="/var/log/apache2/access.log"

if [ "$1" = "config" ]; then

        echo 'graph_title Apache Error Rate '
        echo 'graph_category apache'

        echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel rate'
        echo 'graph_scale no'

	for code in $mystatuscodes
		do
		echo "${code}.label ${code} Errors"
	done

        echo 'graph_info The number of apache errors in logs'
        exit 0
fi

        for code in $mystatuscodes
                do
		echo -n "${code}.value "
		tail -${myloglines} ${myaccesslog} | awk '{print $9 }' | grep -c "${code}"
        done

exit 0
